name: Compare Versions Firmware

on:
  push:
    branches:
      - TFT_1.44_SPI

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq for JSON processing
        run: sudo apt-get install jq

      - name: Extract versions from JSON, header, and bin files
        id: extract_versions
        run: |
          json_version=$(jq -r '.main.version' main/src/include/Info_prod.json)
          header_version=$(awk -F '"' '/FirmwareVer/{print $2}' main/src/include/Macro_define.h)
          bin_version=$(strings build/main.ino.bin | grep -E 'v[0-9]+(\.[0-9]+){2}' | head -n 1)
          echo "json_version=$json_version" >> $GITHUB_OUTPUT
          echo "header_version=$header_version" >> $GITHUB_OUTPUT
          echo "bin_version=$bin_version" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          if [ "${{ steps.extract_versions.outputs.json_version }}" == "${{ steps.extract_versions.outputs.header_version }}" ] && [ "${{ steps.extract_versions.outputs.json_version }}" == "${{ steps.extract_versions.outputs.bin_version }}" ]; then
            echo "All versions match: ${{ steps.extract_versions.outputs.json_version }}"
          else
            echo "Versions do not match"
            exit 1
          fi
