name: Compare Versions Firmware

on:
  push:
    branches:
      - master

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq for JSON processing
        run: sudo apt-get install jq

      - name: Extract versions from JSON, header, and bin files
        id: extract_versions
        run: |
          json_version=$(jq -r '.main.version' include/Info_prod.json)
          header_version=$(awk -F '"' '/FirmwareVer/{print $2}' include/Macro_define.h)
          bin_version=$(strings build/main.ino.bin | grep -E 'v[0-9]+(\.[0-9]+){2}' | head -n 1)
          echo "json_version=$json_version" >> $JSON_VERSION
          echo "header_version=$header_version" >> $HEADER_VERSION
          echo "bin_version=$bin_version" >> $BIN_VERSION

      - name: Compare versions
        run: |
          if [ "${{ steps.extract_versions.outputs.$JSON_VERSION }}" == "${{ steps.extract_versions.outputs.$HEADER_VERSION }}" ] && [ "${{ steps.extract_versions.outputs.$JSON_VERSION }}" == "${{ steps.extract_versions.outputs.$BIN_VERSION }}" ]; then
            echo "All versions match: ${{ steps.extract_versions.outputs.$JSON_VERSION }}"
          else
            echo "Versions do not match"
            exit 1
          fi
